### ISSUE TITLE
Color Picker returning Hex Values when RGB is required

### ISSUE THREAD

**Issue by brotherlu** [alexandercerutti/passkit-visual-designer#17]
According to [PassKit Package Format Reference](https://developer.apple.com/library/archive/documentation/UserExperience/Reference/PassKit_Bundle/Chapters/TopLevel.html#//apple_ref/doc/uid/TP40012026-CH2-SW1) colors need to be in RGB notation rather than Hex.

**Comment by alexandercerutti** [comment]
Hey @brotherlu!
Thanks for using passkit-visual-designer!

I know that, but when I created it, I used an external library that offered several alternatives and this was the most suitable one, graphically speaking.

But don't worry, when it will be time to export your pass, colors are going to get saved as RGB!

Look at it here: https://github.com/alexandercerutti/passkit-visual-designer/blob/65aee4d6a8daaa4b12e5568bdaf0272030333e4a/src/Configurator/OptionsMenu/pages/PanelsPage/Panel/ColorPanel/index.tsx#L44

Hope you are satisfied with PKVD 😊
Let me know if I can help you any further!

**Comment by brotherlu** [comment]
Hey @alexandercerutti 
Fantastic, I was just confused with the UI since it was in Hex. 
Thanks PKVD it is a fantastic tool.

**Comment by alexandercerutti** [comment]
Good to know! Thank you!
I'll use this feedback for future improvements for when I'll have some spare time 😉

Sadly I don't have any analytics systems on it so I'm not very aware of how many people use it and if I should give some priority to it!

May I ask you how you found it?

**Comment by brotherlu** [comment]
I found PKVD through passkit-generator. I am build a small tool for passkit-generator and I am using PKVD to create passes to test.

**Comment by alexandercerutti** [comment]
Oh, are you building a tool **for** passkit-generator? I am really curious now, eheh!
Nice to know anyway!

**Comment by alexandercerutti** [comment]
I'm closing this since this is not an issue ;)
Thank you again for using passkit-visual-designer @brotherlu!
